---
# nginxのインストール先でAmazonExtras有効化
- name: Enable amazon-linux-extras packages
  become: yes
  shell: "amazon-linux-extras enable {{nginx_version}}"

# nginxをyumでインストール
- name: install nginx from amazon extras
  become: yes
  yum: 
    name: nginx
    state: present
    lock_timeout: 180

# nginxを動作させるユーザーをec2-userへ変更する
- name: Comment out the user that works Nginx nginx user
  become: yes
  lineinfile:
    path: /etc/nginx/nginx.conf
    state: present
    backrefs: "yes"
    regexp: '^(user nginx;)$'
    line: 'user ec2-user;'

# nginxの自動起動有効化と起動
- name: Set auto start nginx
  become: yes
  command: systemctl enable nginx

- name: Set restart nginx
  become: yes
  command: systemctl restart nginx