---
- name: Playbook for rails-tutorial
  hosts: production
  become: yes
  roles:
    - { role: common, tags: common }
    - { role: git, tags: git}
    - { role: mysql, tags: mysql }
    - { role: nginx, tags: nginx }
    - { role: nodejs, tags: nodejs }