---
# sudo実行時にユーザー定義のパスを引き継ぐ
- name: Comment out default secure_path
  become: yes
  lineinfile:
    path: /etc/sudoers
    state: present
    backrefs: "yes"
    regexp: '^(Defaults    secure_path =.*)$'
    line: '#\1'
    validate: '/usr/sbin/visudo -cf %s'

# 以下の書き方では、最終行にline:で指定した文字列が追記し続けられるのでNG
# 参考 https://qiita.com/Ki2neudon/items/b43b68e48f4e403266ce#comment-dd5261a37f5a509ebd31
# - name: Comment out of default source_path
#   become: yes
#   lineinfile:
#     path: /etc/sudoers
#     state: present
#     regexp: '^Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/bin'
#     line: '# Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/bin'
#     validate: '/usr/sbin/visudo -cf %s'

- name: Enable env_reset and env_keep for PATH
  become: yes
  blockinfile:
    path: /etc/sudoers
    state: present
    regexp: '^# Defaults   env_keep += "HOME"'
    content: |
      Defaults   env_reset
      Defaults   env_keep += "PATH"
    validate: '/usr/sbin/visudo -cf %s'

# アプリケーションの実行ディレクトリ作成
- name: Create RailsTutorial app dir
  become: yes
  file:
    path: /home/vagrant/workspace
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user_group }}"
    mode: 0755